feature/frontend_exam into develop
upb-uc4/api pull request #107
Opened 2021-01-26 09:53 UTC by dhelmert

### Reason for this PR
- Exams are now part of UC4, and need an api

### Changes in this PR
- Added exam-management.yaml
- Added examresult-management.yaml
- Updated admission-management to include exam admissions

2021-01-26 10:18 UTC, RHelmert approved these changes

2021-01-26 10:47 UTC, bastihav requested changes
- [x] for all lists parameters: specify that we need a comma seperated value
- [x] example description for UnsignedProposals are wrong (admission, exam, examresult)
- [x] specify "admittableAt" and "droppableAt" format -> ISO
- [ ] specify admittableUntil and droppableUntil format in schema -> date iso

2021-01-26 10:47 UTC, bastihav commented on exam-management.yaml
> +                description: "URI of the newly created Admission"
```suggestion
```

2021-01-26 10:47 UTC, bastihav commented on examresult-management.yaml
> +                description: "URI of the newly created Admission"
```suggestion
```

2021-01-26 15:19 UTC, bastihav approved these changes

2021-01-26 15:35 UTC, NikoBergemann reviewed
Nothing out of the ordinary

2021-01-26 18:21 UTC, bastihav requested changes
we now have two superflous endpoints (for resolving single enrollmentId and single username respectively), which should be removed

2021-02-02 10:12 UTC, dhelmert commented
> 
> 
> we now have two superflous endpoints (for resolving single enrollmentId and single username respectively), which should be removed

Good point, the endpoints in certificate are now removed

2021-02-03 15:02 UTC, bastihav approved these changes

2021-02-03 15:02 UTC, bastihav commented on exam-management.yaml
> +  version: "0.16.1"
```suggestion
  version: "0.17.1"
```

2021-02-03 15:02 UTC, bastihav commented on exam-result-management.yaml
> +  version: "0.16.1"
```suggestion
  version: "0.17.1"
```

2021-02-03 15:04 UTC, bastihav approved these changes

2021-02-03 15:04 UTC, bastihav commented on admission-management.yaml
> +  version: "0.16.1"
```suggestion
  version: "0.17.1"
```

2021-02-03 15:19 UTC, merged