Generalize ApprovalDenied/RejectionDenied to ParticipationDenied
upb-uc4/api pull request #115
Opened 2021-02-23 10:21 UTC by matthias-geuchen

### Reason for this PR:
- to avoid leaking sensitive data, transactions should only be executable by users required to approve the transaction

### Changes in this PR:
- generalize approval denied and rejection denied errors to participation denied error
- add participation denied error to errors throwable by transactions utilizing our operation workflow
- outsource errors related to our operation workflow from transactions to general error definition

2021-02-23 10:49 UTC, NikoBergemann approved these changes

2021-02-23 13:40 UTC, dhelmert requested changes
While i approve of generalizing the approval and rejection errors into Participation errors, I do not think that putting the "HLInsufficientApprovals" and "ExecutionImpossible" errors into the errors file is a good idea.
A problem with the current api is that whenever you inspect a specific call, there can be some really important information (like which initiate an operation or the fact that everything can be a proposal) somewhere else. I think that this is, in the example cases, acceptable. 
However, it is my opinion that having the errors a call can return in a general file, instead of at the specific call, significantly harms readability.

2021-02-23 13:40 UTC, dhelmert commented on hlf/chaincode/contracts/operation.md
> +        "title": "You are not allowed to participate in the given operation"
```suggestion
        "title": "You are not allowed to approve or reject the given operation"
```

2021-02-23 13:40 UTC, dhelmert commented on hlf/chaincode/contracts/operation.md
> +        "title": "You are not allowed to participate in the given operation"
```suggestion
        "title": "You are not allowed to approve or reject the given operation"
```

2021-02-23 13:40 UTC, dhelmert commented on hlf/chaincode/contracts/operation.md
> +        "title": "You are not allowed to participate in the given operation"
```suggestion
        "title": "You are not allowed to approve or reject the given operation"
```

2021-02-23 14:06 UTC, matthias-geuchen commented on hlf/chaincode/errors.md
> +    "title": "You are not allowed to participate in the given operation"
```suggestion
    "type": "HLAccessDenied",
    "title": "You are not allowed to execute in the given transaction"
```

2021-02-23 14:06 UTC, matthias-geuchen commented on hlf/chaincode/errors.md
> +In the following, the specific error that can be returned by every transaction not part of the [OperationContract](./contracts/operation.md#OperationApi)  due to our operation workflow.
```suggestion
In the following, the specific error that can be returned by every transaction due to our operation workflow.

```

2021-02-26 11:35 UTC, RHelmert commented on hlf/chaincode/errors.md
> +    "type": "HLParticipationImpossible",
```suggestion
    "type": "HLExecutionImpossible",
```

2021-03-01 14:24 UTC, dhelmert approved these changes

2021-03-01 14:25 UTC, RHelmert approved these changes

2021-03-01 15:02 UTC, bastihav approved these changes

2021-03-01 16:33 UTC, merged