Adapt API to JWT authentication
upb-uc4/api pull request #30
Opened 2020-08-24 15:45 UTC by ldklenner

### Reason for this PR
- Lagom now uses token authentication

### Changes in this PR
- AuthenticationService now provides additional endpoints:
  - `login`: retrieve login and refresh token
  - `refresh`: retrieve new login token
  - `logout`: invalidate tokens
 - All other API calls now expect token authentication

2020-08-26 12:53 UTC, lrschaef approved these changes

2020-08-26 15:29 UTC, dhelmert approved these changes

2020-08-26 15:37 UTC, dhelmert commented
This Closes #30

2020-08-28 11:46 UTC, bastihav requested changes
https://swagger.io/docs/specification/authentication/cookie-authentication/

we should add the "Set-Cookie" header to login and refresh endpoints and give an example token, etc.

2020-08-28 15:28 UTC, bastihav approved these changes

2020-08-28 18:29 UTC, merged