Refactor invalidParams naming scheme
upb-uc4/api pull request #39
Opened 2020-09-07 07:54 UTC by matthias-geuchen

### Reason for this PR
- the chaincode api should precisely specify, which parameter/field of which parameter could not be parsed

### Changes in this PR
- add names for the parameters of each transaction
- change the naming-scheme for the ```invalidParams``` to first state the name of the faulty transaction parameter 
- merge somewhat duplicate errors *unprocessable field* and *unprocessable entity* to be represented by *unprocessable entity*

2020-09-07 08:39 UTC, david-buderus requested changes

2020-09-07 08:39 UTC, david-buderus commented on hyperledger_matriculation_api.md
> +        "type": "hl: unprocessable entity",
This will get in conflict with #37
Better to use the new notation

2020-09-07 08:39 UTC, david-buderus commented on hyperledger_matriculation_api.md
> +        "type": "hl: unprocessable entity",
This will get in conflict with #37
Better to use the new notation

2020-09-07 14:32 UTC, NikoBergemann approved these changes

2020-09-09 07:15 UTC, david-buderus requested changes

2020-09-09 07:15 UTC, david-buderus commented on hyperledger_matriculation_api.md
> +        "title": "The following parameters do not conform to the specified format.",
We don't use points at the end of a title

2020-09-09 07:15 UTC, david-buderus commented on hyperledger_matriculation_api.md
> +        "title": "The following parameters do not conform to the specified format.",
We don't use points at the end of a title

2020-09-09 07:15 UTC, david-buderus commented on hyperledger_matriculation_api.md
> +        "title": "The following parameters do not conform to the specified format.",
We don't use points at the end of a title

2020-09-09 07:57 UTC, bastihav approved these changes

2020-09-09 08:01 UTC, david-buderus approved these changes

2020-09-09 08:32 UTC, dhelmert approved these changes

2020-09-09 09:34 UTC, merged