Feature/certificate management
upb-uc4/api pull request #48
Opened 2020-09-21 14:05 UTC by dhelmert

### Reason for this PR
- The certificate handling for signing transactions needs an api

### Changes in this PR
- Added certificate api, with newly defined objects and endpoints

2020-10-06 08:06 UTC, bastihav commented on certificate-management.yaml
> +            types: Validation, LoginTokenSignatureInvalid
do you validate the CSR? or what is validated here?

you could validate using openssl e.g.

2020-10-06 08:06 UTC, bastihav commented on certificate-management.yaml
> +  /certificates/{username}/enrollmentId:
who is allowed? do we need a 403?

2020-10-06 08:06 UTC, bastihav commented on certificate-management.yaml
> +  /certificates/{username}/privateKey:
404 if user has not done certification stuff?

2020-10-06 08:06 UTC, bastihav commented on certificate-management.yaml
> +          iv: "this is an iv"
```suggestion
          iv: "hbhRVb7R99xsHh3J"
```

2020-10-06 08:06 UTC, bastihav commented on certificate-management.yaml
> +          key: "thisIsAnEncryptedPrivateKey"
```suggestion
          key: "3eA8l6HeaDwyTxbYg9tKsp7AjKSS8RBvuYsahI86B7MI1hGIJgaM/6ylWszGEoS4pEbX59Wh6ssv9blmWk1/DkJrgqsrUgn+mrlO+pQwfqltUFOWOsfyPwEONEfO4baWyrnq5mQypj2TYEx79Kg8Pxx/iZbAxMRTESMztVMlHBTcZShVeEvVV+EI+HMuGsYpJE109G6BLSk4YoxEootHmooqyAZqOpBaJqcNnZWKnYAsANdoL0dv+0irOTkUpc+eYJwBmHQkxOOBfLHKyehIk5lTRFrmjcvFNt7i8arqqQqMla8iU8KbCQcbVDlcGVNPResxlYndXbyyZEXeQqHXrZ5lUQYFm9YgHkTlwAzkhBDJ+fDSC817eyKGZrO/yP7FyaCAFmzGjzP2rqNQTwFcHhwORbFAP9Z32IXIxfxLFumwNa/tmjZXfyr9ZoHgnmMoOtKzeow3KaZNPmdNWHl8Ce3nmfMSKhYmpjMTfVP+UH55OG3qQiHKiucKOT5wQ4ZD5veyFrwoLhxcmJ6rNAeOAg+5z38om3/e60himBmfP80t/HmzTytVO9sv4YnGyfFabCSP7dtuzwjl2No2xW00wmgmsyu9eA1+I9qW7kOM9a3+LmADmnkJxqOmFZ4/iDw0i6YkCjmIAKZVqcCxG5mGeBwU+54wfL2sF+eE2h0WWSobNFAy3NctyF8BV4zz/4GBNzGSG2AbHHXhF0go1CQLuzJzhePp6o8oRjBGtVr2EXSaNxsZbu5hNomFuvZmVLD/KU9BldJ4N4oMwH/M1lxjMxB94MelKVgn5ye7tZ5rkKslND/SRauS0vO1rK36FZG0fZ9agDX1iZkzpCuVDcfkQ6MyOhf99KvDBAdmpPcJNAlNq67P435g5NSe69rPKTAgsYUO6HTrvcDR3WOxls/L+SS3LFymokBP6uWrLPzkgwPWRph84HxKnlljZeUcjRc7K0pqdJTkIBxa1PGQXw+O4e0yMZ8abyvOBNH8eKVa47sP2jcqTFlECJwx9/5XLbM5mCK8IBQci5HRnux+p0Dj6wCRyYptLGdKsins182edK85LVUWR1dVcq+Ub6KJlks5rFNGwbPZ+hteeMUuia0k5F4aWNVizw2aHww/hPGueZckiAnV7o1IlfCvOjyzxvQvmXQOe0j11E4ZWh+GtxjcAwBIEl0w5qURFY7pPgX0w+d7XTq3PUaLSWXGBeAecPshfFFiwzeIYg5/wWP1Sq5OzXCwyUKrf/VeJWjsfyTy6rkWtYwxrL/fztj1E6RLWV5W+vA2QC8b0zfEgzs4g8I3FrSEnqI37CFQZxygJaKRPcp+3bA34quQkGyaL+jz/rZQ8wFDqfF0tg339GQ2A5kvdcCFCFDs5t3YOu1nkBwKtP5l0JQqY+7j4Ju070P0BrrfpF0RBXaLwzBrScpswOzGp2TvzMmie8BPGuB3gOeHPkz1SO5iWSnYzGmLxAc47TAAfjAXEuEB0X87oS1LG1fmslR2rI4cHsdSiC35Pq497GRS2aXz9gw8vyU50+xz5FhD9j3Cj0yPlR92A7EXtT+OozTRbi5DkuLf2O0ThnH+0AMzxd4k8zEtAVQmR6COIbZ7KHmBfzq3mkcjIeLildCHmFMfYysdztVQw4o+Bq7B4YF00Apdgu5Rskrg/Z4L9k9FEP93wVS4QZZtXW4q7Yg0ZqIJ2HhHqZ4EX97vdSSpZ1aJmS9oGJptDK13cbPBfOlIIYjRNRirJDPfglP2iLsIc5xYVa1LJamA+3/9JBpknBlV7iXILnnDSTfcxonvRQL0WArv0LpWVmN0fenykLj5f1hXQkVcxS+pmXqXUpgeGkrCwbQcDUOdRjt3OVoY0DjB9JdoKuQZdDX0a4eSe8UdSb16TNDEU5nX1gXxCLX8ReLw4fN6oaRGyxa+eZ6x0KcXepTGXjLLZhB0rtElbKFZl2hRPhpMVKzyC6aKtBCvuu9SlZXtdfeAhwozFXj+E5v++GxMn50P/Mrsbqv0/Vr+ulLFW0nSHi6qop1sGbb3iv4lHUmNiz5V1dEdhi3/hjamOoZxc913jzJUNbrTf0CIMuWBWV9rk8Gk+tKkdjukLnFA0ja1LU9f9czI86UkyaG6pUUHESbSCCqTjSQUfURR04obhnMkc5B4lnN71eOlFORnek/2xBI/PNjHQ+sA2JJb58dvJWm2kBSTWTOclahvKAyucBTtWUpi784XolFOMKEzktKEwKEZdpc3yvREaWt3iLECivdVqcV7O2W3ACDNRjaJvOfK0sL8YLhADDdcrdjlnZf/kyn6E/4J7oX4p2uTfwLXVgWlREIkiij8g26QwAhfXBa5BcF9vc2O4jR42er1dh82Sj1CywE3gUvdkAu0MRNduNZIcBHS6PRIKBIdMyN2jVKiMwAc5tnbEfMRSs6+O9tDYwPS1vqDsODBIbkGnpZHiYhXCdhohBayR2JoMpCz23YPeflQuWLYNMDbVCbdxKsPppv0R901vJvLRxH3kT1DqhUyR+t3jR++0ssnUzt2Nex1luWr7UXnyNfHPaSYRHViEiT0GuT96S+4i/llTCrFwqbp4laTB4Rw2pigjMAwJl3fg8rYrMEMInD0FBVfe3nWgpxN5qmycEyqGzpdm4jZc5ap8o4PfwoBgETuVxzGYoXHLsTpcuj3euwA8oTVG4fGina95LfwGhrp+JFsnlX96zBQonEq25uLzvkeFKM/e4dXTpma29b+QQ6sad3u5lE30meZbN8wpGutLWuNVZbmbAde5GqzRt3gFUp0Bzz3ehqZzKy/hcnfDfYwtsj82GCbxUDgjDLyGIQ0p/T1m5HoThGJd3a1cZ6f7+pLiwxcAP1EEyUfXRDmhI59380JHUgzoSbRO4z68NRXGdRFNo305YTDB1Wj9W+zq3xCcufzLr4AZk5PhNVSGg0oSO7+M9kDgigpWOMwUy+nZA7+1HHIMYWixc1MTOmYJJcsJgnBTrCe14y/zwfAUdNCOab30BRMWLKSR6dKKL4asZnvsz71pr/Jy8e5UyKU1RINg52TpvVIroDbf+BUZLLHdlnL7W6Q2VoloPNctQhacpvBLMD5bi0sPhbnCZ4jQpI5KZpOMNBdeUAueL2zP1yYNDJ1VYtnu9yHjo1hVxRdx8RsLykHmSat1Y8cIh1EnaSWFT5UUHeJJndIu/4YmIpWlTVbNSkUZssB"
```

2020-10-06 08:06 UTC, bastihav commented on certificate-management.yaml
> +          salt: "this is a salt"
```suggestion
          salt: "tF/A9PnUBkctJNWam7rQj3hu17hg1TGpQdVVOPC1YN8="
```

2020-10-06 11:03 UTC, dhelmert commented on certificate-management.yaml
> +            types: Validation, LoginTokenSignatureInvalid
We only validate that the encrypted private key data structure is either completely empty, or all parameters set, as a partially defined private key object  makes no sense. The CSR itself is not validated

2020-10-06 11:16 UTC, dhelmert commented on certificate-management.yaml
> +  /certificates/{username}/privateKey:
We defined a new 404 error;
type: "NotEnrolled"
title: "Enrollment of the user is required before the requested resource can be fetched"
We failed to add this to the api, change incoming

2020-10-06 11:48 UTC, dhelmert commented on certificate-management.yaml
> +  /certificates/{username}/enrollmentId:
One can only fetch the enrollmentId of themself, which is now represented by the possible 403 Owner Mismatch error

2020-10-08 07:51 UTC, bastihav commented on certificate-management.yaml
> +  /certificates/{username}/enrollmentId:
We discussed this on the user branch too, the enrollmentId is public (included in certificates), do we keep this error? Which service (user or certificate management) will expose the enrollmentId?

2020-10-08 08:37 UTC, lrschaef requested changes

2020-10-08 08:37 UTC, lrschaef commented on certificate-management.yaml
> +      description: "Send the CSR, and optionally the encrypted private key, to start the certificate creation process. One can only invoked this process for themselves."
```suggestion
      description: "Send the CSR, and optionally the encrypted private key, to start the certificate creation process. One can only invoke this process for themselves."
```

2020-10-08 08:37 UTC, lrschaef commented on certificate-management.yaml
> +        description: "Username of the user whose private is fetched"
```suggestion
        description: "Username of the user whose private key is fetched"
```

2020-10-08 08:37 UTC, lrschaef commented on certificate-management.yaml
> +      summary : "descr"
```suggestion
      summary : "PostMessageCsr Example"
```
This looks very weird in the editor. You may use my suggestion or write a small summary yourself. Note that this is the text that appears in the example dropdown, so it should be short.

2020-10-08 09:16 UTC, dhelmert commented on certificate-management.yaml
> +  /certificates/{username}/enrollmentId:
We will make the call less restricted in permissions. For both enrollmentId and certificate fetching we will change the access rights to include authentication (but allows all roles). As you pointed out, fetching enrollmentId should have the same authentication restrictions as fetching certificates.
The enrollmentId fetching will be included in the CertificateService, and not in the UserService. The other PR will be adapted

2020-10-08 09:52 UTC, dhelmert commented on certificate-management.yaml
> +  /certificates/{username}/enrollmentId:
The above changes are now applied to both code and api documentation

2020-10-08 09:59 UTC, lrschaef approved these changes

2020-10-08 13:38 UTC, bastihav approved these changes

2020-10-09 11:53 UTC, merged