Update UserService api to include new DELETE Image call
upb-uc4/api pull request #53
Opened 2020-09-28 11:52 UTC by dhelmert

### Reason for this PR
- While images were updatable, one was not able to delete their profile picture, or reset to default
- PUT call was missing the location header for the newly created image

### Changes in this PR
- Add location header to PUT image
- Add endpoint DELETE image, which deletes the profile picture, effectively resetting to default

2020-09-28 11:58 UTC, lrschaef requested changes

2020-09-28 11:58 UTC, lrschaef commented on user-management.yaml
>                    - $ref: '#/components/schemas/DetailedError'
```suggestion
            types: MalformedLoginToken, MultipleAuthorizationError
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/GenericError'
```
Deserialization and MissingHeader cannot occur here. Therefore, no DetailedError can be returned.

2020-09-28 11:59 UTC, lrschaef approved these changes

2020-09-29 12:10 UTC, bastihav approved these changes

2020-09-29 13:07 UTC, merged