first draft contract API
upb-uc4/api pull request #65
Opened 2020-10-21 09:58 UTC by NikoBergemann

2020-10-21 10:42 UTC, nklsd requested changes

2020-10-21 10:42 UTC, nklsd commented on hlf/chaincode/draft.md
> +- ID = getCertificate
```suggestion
- ID = getSignatures
```

2020-10-21 10:42 UTC, nklsd commented on hlf/chaincode/draft.md
> +      - Description: This error is returned, if the state of data on the ledger is not consistent with the curent model. This error should only occurr if the model changes while the old ledger state
```suggestion
      - Description: This error is returned, if the state of data on the ledger is not consistent with the current model. This error should only occur if the model changes while the old ledger state remains without modification.

```

2020-10-21 10:42 UTC, nklsd commented on hlf/chaincode/draft.md
> +    -
```suggestion

```

2020-10-21 10:42 UTC, nklsd commented on hlf/chaincode/draft.md
> +### Get Signatures
```suggestion
### GetSignatures
```

2020-10-21 10:44 UTC, nklsd approved these changes

2020-10-21 17:02 UTC, matthias-geuchen reviewed
Few things I'd like to discuss

2020-10-21 17:02 UTC, matthias-geuchen commented on hlf/chaincode/draft.md
> +    - hash(transactionName, params) :: String
I'd just pass the transactionName and params to the transaction. This way we can do all hashing in chaincode and do not have to worry about that anywhere else.

2020-10-21 17:02 UTC, matthias-geuchen commented on hlf/chaincode/draft.md
> +  "transactionHash": "string",
The transactionHash would then be unnecessary here.

2020-10-23 15:15 UTC, matthias-geuchen approved these changes

2020-10-26 14:04 UTC, merged