Add Hyperledger version endpoints
upb-uc4/api pull request #87
Opened 2020-12-01 09:41 UTC by dhelmert

### Reason for this PR
- For transparency and for more info in bug reports, we decided on a new endpoint that reveals the hyperledger versions (scala-api and chaincode) on every Service communication with Hyperleder

### Changes in this PR
- Added endpoints and objects for sending the hyperledger versions (scala-api and chaincode)
- Renamed version objects to better reflect content

2020-12-02 18:22 UTC, bastihav reviewed
Did the configuration management hyperledger version endpoint change? IIRC, configurationManagement does not have any hyperledger connection, right? So chaincode and API versions are meaningless here.

2020-12-03 10:01 UTC, dhelmert commented
> Did the configuration management hyperledger version endpoint change? IIRC, configurationManagement does not have any hyperledger connection, right? So chaincode and API versions are meaningless here.

Good point, the object is now refactored to only contain the network version.

2020-12-08 12:24 UTC, lrschaef approved these changes

2020-12-15 16:15 UTC, bastihav requested changes
/version/hyperledger
is usually the cc + api version endpoint, we should rename this to  /version/hyperledger-network or similar. I can not suggest, because you did not change anything here.

2021-01-04 11:02 UTC, bastihav approved these changes

2021-01-06 12:56 UTC, merged