Return SubmissionResult containing existing AND missing approvals
upb-uc4/api pull request #90
Opened 2020-12-08 09:42 UTC by NikoBergemann

2020-12-08 14:12 UTC, matthias-geuchen approved these changes

2020-12-09 12:01 UTC, dhelmert requested changes

2020-12-09 12:01 UTC, dhelmert commented on hlf/chaincode/approval.md
> +      "Users"
```suggestion
      "Student"
```

2020-12-09 12:01 UTC, dhelmert commented on hlf/chaincode/approval.md
> +      "Users"
If im not mistaken, the groups are the same groups are the one in Lagom, which means "Admin", "Lecturer" and "Student".

2020-12-09 12:01 UTC, dhelmert commented on hlf/chaincode/approval.md
> +    "Users"
```suggestion
    "Student"
```

2020-12-09 12:02 UTC, NikoBergemann commented on hlf/chaincode/approval.md
> +      "Users"
As of now, the groups are arbitrary, you can put whatever you want into those.
Student is fine though, I'll commit the suggestion

2020-12-09 12:55 UTC, dhelmert approved these changes

2020-12-09 12:55 UTC, dhelmert commented on hlf/chaincode/approval.md
> +  "existingApprovals": {
```suggestion
{
  "operationId" : "0424974c68530290458c8d58674e2637f65abc127057957d7b3acbd24c208f93",
  "existingApprovals": {
```

2020-12-09 13:23 UTC, bastihav approved these changes

2020-12-09 14:05 UTC, merged