Feature/group api
upb-uc4/api pull request #91
Opened 2020-12-08 12:49 UTC by anemonekk

2020-12-08 14:26 UTC, mco33415 approved these changes

2020-12-08 14:31 UTC, matthias-geuchen approved these changes

2020-12-09 09:45 UTC, anemonekk commented on hlf/chaincode/group.md
> +        - Description: ledgerState after transaction.
```suggestion
- Receive
    - group :: [Group](#Group)
        - Description: ledgerState after transaction.
```

2020-12-09 09:47 UTC, NikoBergemann approved these changes

2020-12-09 14:15 UTC, dhelmert requested changes

2020-12-09 14:15 UTC, dhelmert commented on hlf/chaincode/group.md
> +        - Description: ledgerState after transaction.
```suggestion
    - ""
      -  Description: Done; returns empty String on success.
```

2020-12-09 14:15 UTC, dhelmert commented on hlf/chaincode/group.md
> +    - groupID :: String
```suggestion
    - enrollmentId :: String
    - groupId :: String
```

2020-12-09 14:15 UTC, dhelmert commented on hlf/chaincode/group.md
> +    - groupID :: String
```suggestion
    - enrollmentId :: String
    - groupId :: String
```

2020-12-09 14:15 UTC, dhelmert commented on hlf/chaincode/group.md
> +            - Description: ledgerState after transaction.
```suggestion
    - ""
      -  Description: Done; returns empty String on success.
```

2020-12-09 14:15 UTC, dhelmert commented on hlf/chaincode/group.md
> +          - Description: Exhaustive List of all group names the user is part of.
```suggestion
          - Description: Exhaustive List of all groupIds the user is part of.
```

2020-12-09 14:15 UTC, dhelmert commented on hlf/scala/group.md
> +        - => Success
```suggestion
    - ""
    => Success
```

2020-12-09 14:15 UTC, dhelmert commented on hlf/scala/group.md
> +        - => Success
```suggestion
    - ""
    => Success
```

2020-12-09 14:15 UTC, dhelmert commented on hlf/scala/group.md
> +    - groupList :: List\<String\>
```suggestion
    - userList :: List\<String\>
```

2020-12-09 14:15 UTC, dhelmert commented on hlf/scala/group.md
> +    - groupList :: List\<String\>
```suggestion
    - groupIdList :: List\<String\>
```

2020-12-09 14:15 UTC, dhelmert commented on hlf/chaincode/group.md
> +    - groupList :: List\<String\>
```suggestion
    - groupIdList :: List\<String\>
```

2020-12-09 14:25 UTC, RHelmert commented on hlf/scala/group.md
> +    - groupList :: List\<String\>
resolve this and get my approval

2020-12-09 14:32 UTC, dhelmert requested changes

2020-12-09 14:32 UTC, dhelmert commented on hlf/chaincode/group.md
> +      -  Description: Done, returns the submitted data.
```suggestion
      -  Description: Done; returns empty String on success.
```

2020-12-09 14:32 UTC, dhelmert commented on hlf/chaincode/group.md
> +  "userList": ["0123456", "123"]
```suggestion
  "userList": ["EnrollmentIdExample123", "EnrollmentIdExample124"]
```

2020-12-10 11:46 UTC, RHelmert approved these changes

2020-12-11 12:16 UTC, dhelmert approved these changes

2020-12-11 12:17 UTC, merged