operation Contract
upb-uc4/api pull request #93
Opened 2020-12-15 09:13 UTC by NikoBergemann

- approvalContract --> operationContract
- adjust operationContract to new Requirements
- provide public scala Interface for Operations

2020-12-15 09:52 UTC, anemonekk commented on hlf/scala/operation.md
> +For "admission" handling we offer the following interface.
change to "operation"

2020-12-15 12:11 UTC, NikoBergemann commented on hlf/scala/operation.md
> +For "admission" handling we offer the following interface.
```suggestion
For "operation" handling we offer the following interface. 

```

2020-12-15 12:12 UTC, NikoBergemann commented on hlf/chaincode/operation.md
> +
```suggestion
### GetOperations
- ID = getOperations
- Send
    - enrollmentId :: String (optional)
    - state :: String (optional)
- Receive
    - operationsList :: List\<[OperationData](#OperationData)\>
      - Description: Returns the full list of existing Operations matching the filter parameters.
        If these parameters are empty, the exhaustive list of all existing Operations is returned.

```
Remove faulty error. If a single operation could not be rea we stil want to return as many "working" operationData as possible

2020-12-15 13:46 UTC, anemonekk commented on hlf/scala/operation.md
> +## GetOperation(operationId: String)
```suggestion
## GetOperationData(operationId: String)

```

2020-12-15 14:49 UTC, bastihav approved these changes

2020-12-15 17:17 UTC, mco33415 approved these changes

2020-12-15 17:26 UTC, matthias-geuchen requested changes

2020-12-15 17:26 UTC, matthias-geuchen commented on hlf/chaincode/operation.md
> +    - contractName, transactionName, param1, ..., paramN :: String
```suggestion
    - contractName, transactionName :: String
    - params :: List\<String\>

```

2020-12-15 17:26 UTC, matthias-geuchen commented on hlf/chaincode/operation.md
> +
```suggestion

- [GenericError](errors.md#GenericError) 
      ```json
      {
        "type": "HLNotFound",
        "title": "There is no Operation for the given operationId"
      }
      ```
      - Description: This error is returned, if there is no operation for the specified operationId present on the ledger.
```

2020-12-15 17:26 UTC, matthias-geuchen commented on hlf/scala/operation.md
> +        - => error is returned
```suggestion
        - => error is returned
          - If the operationId is not present on the ledger.
```

2020-12-15 17:26 UTC, matthias-geuchen commented on hlf/scala/operation.md
> +            inputs "enrollmentId", "state".
```suggestion
            inputs "operationId", "state".

```

2020-12-15 17:26 UTC, matthias-geuchen commented on hlf/scala/operation.md
> +## GetOperations(enrollmentId: String, state: String)
```suggestion
## GetOperations(operationId: String, state: String)

```

2020-12-15 17:26 UTC, matthias-geuchen commented on hlf/chaincode/operation.md
> +
```suggestion

- [GenericError](errors.md#GenericError) 
      ```json
      {
        "type": "HLNotFound",
        "title": "There is no Operation for the given operationId"
      }
      ```
      - Description: This error is returned, if there is no operation for the specified operationId present on the ledger.
```

2020-12-15 17:26 UTC, matthias-geuchen commented on hlf/scala/operation.md
> +        - => error is returned
```suggestion
        - => error is returned
          - If the operationId is not present on the ledger.
```

2020-12-16 13:48 UTC, NikoBergemann commented on hlf/chaincode/operation.md
> +  },
```suggestion
    "parameters": "[
      \"EnrollmentID_001\",
      \"legit_certificate\"
    ]"
  },

```

2020-12-16 14:07 UTC, anemonekk commented on hlf/chaincode/operation.md
> +      -  Description: Success, returns the list of approvals.
```suggestion
      -  Description: Success, returns the list of operations.

```

2020-12-17 13:14 UTC, RHelmert approved these changes

2020-12-17 17:17 UTC, matthias-geuchen approved these changes
Looks good, apart from a small inconsistency between OperationData and TransactionInfo models.

2020-12-17 17:17 UTC, matthias-geuchen commented on hlf/chaincode/operation.md
> +  ]
```suggestion
  "parameters": "[
    \"EnrollmentID_001\",
    "\legit_certificate\"
  ]"

```

2020-12-18 12:08 UTC, merged