Feature/multi user signing frontend
upb-uc4/api pull request #96
Opened 2021-01-06 11:33 UTC by dhelmert

### Reason for this PR
- The operation management is needed for Multi-User-Signing, to handle access rights, operation logic and caching

### Changes in this PR
- Add operation-management.yaml with endpoints for fetching operations with various filters

2021-01-06 15:12 UTC, bastihav approved these changes

2021-01-06 15:12 UTC, bastihav commented on operation-management.yaml
> +  version: "0.12.1"
```suggestion
  version: "0.15.1"
```

2021-01-06 15:12 UTC, bastihav commented on operation-management.yaml
> +  - url: https://uc4.cs.upb.de/api/operation-management
```suggestion
  - url: https://uc4.cs.upb.de/api/production/operation-management
```

2021-01-06 15:12 UTC, bastihav commented on operation-management.yaml
> +paths:
hl version missing

2021-01-06 15:12 UTC, bastihav commented on operation-management.yaml
> +        description: "Flag that determines, if only operations that you can approve/deny are fetched"
```suggestion
        description: "Flag that determines, if only operations that you can approve/reject are fetched"
```

2021-01-06 15:12 UTC, bastihav commented on operation-management.yaml
> +        description: "List of states to filter by (PENDING, FINISHED, or REJECTED)"
```suggestion
        description: "Comma-seperated list of operation states to filter by (PENDING, FINISHED, or REJECTED)"
```

2021-01-06 15:12 UTC, bastihav commented on operation-management.yaml
> +      description: "Find course by OperationId"
```suggestion
      description: "Find operation by OperationId"
```

2021-01-06 15:33 UTC, dhelmert commented on operation-management.yaml
> +paths:
Has been added as of now

2021-01-06 15:37 UTC, bastihav approved these changes

2021-01-11 09:58 UTC, bastihav requested changes
examples for matriculation payload are wrong due to approve/reject restructuring

2021-01-19 10:14 UTC, dhelmert commented
> 
> 
> examples for matriculation payload are wrong due to approve/reject restructuring

This is a minimal working api, the new changes, for which these examples are wreong will be coming in another branch

2021-01-19 10:15 UTC, bastihav approved these changes

2021-01-19 10:15 UTC, merged